### ISSUE TITLE
Review/Edit

### ISSUE THREAD

**Issue by TimMorganlive** [loogart/Project-Mountain#9]
During the 'review' when you click edit, it brings you back to the page you want to edit, and then continues through subsequent pages.  Is there a way for it to know that you are in edit, and bring you straight back to the review when done edit?

**Comment by kathp28** [comment]
I agree; you should be able to edit and then go right back to Step 5.

**Comment by loogart** [comment]
@TimMorganlive and @kathp28 great point. What should happen once the software is stitched together on the back end, you should be able to click on the individual steps (kind of like at this point http://127.0.0.1:57062/registration-step5.html). The top bar should remain FILLED UP with green checkboxes during the review process to enable users to easily go from one section to another. Since this is a prototype, no functionality is available.
